dist: xenial
sudo: required
cache:
  directories:
      - $HOME/.m2
      - $HOME/.ccache
      - $HOME/downloads
  timeout: 1000
language: java
services:
      - docker

matrix:
   include:
      - os: linux
        env: PROJ=ffmpeg OS=android-arm
        install: true
        script: ./ci/install-travis.sh
#      - os: linux
#        env: PROJ=ffmpeg OS=android-arm64
#        install: true
#        script: ./ci/install-travis.sh
#      - os: linux
#        env: PROJ=ffmpeg OS=android-x86
#        install: true
#        script: ./ci/install-travis.sh
#      - os: linux
#        env: PROJ=ffmpeg OS=android-x86_64
#        install: true
#        script: ./ci/install-travis.sh